/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileOutputStream;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class TraCuuSinhVienView extends javax.swing.JFrame {

    public TraCuuSinhVienView() {
        initComponents();
        loadsv();
    }

    public void loadsv() {
        String dbURL = "jdbc:sqlserver://127.0.0.1;databaseName=thuvien;user=sa;password=123";
        Connection conn;
        try {
            conn = DriverManager.getConnection(dbURL);

            Statement st = conn.createStatement();
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã Sinh Viên");
            tableModel.addColumn("Tên sinh Viên");
            tableModel.addColumn("DD/MM/YYY");
            tableModel.addColumn("Tên Lớp");
            tableModel.addColumn("Tên Khoa");
            tableModel.addColumn("Giới Tính");
            tableModel.addColumn("Quê Quán");
            tableModel.addColumn("Khóa Học");

            String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString("masv"));
                vt.add(rs.getString("tensv"));
                vt.add(rs.getString("namsinh"));
                vt.add(rs.getString("tenlop"));
                vt.add(rs.getString("tenkhoa"));
                vt.add(rs.getString("gioitinh"));
                vt.add(rs.getString("quequan"));
                vt.add(rs.getString("khoahoc"));

                //Đưa dữ liệu vào TableModel
                tableModel.addRow(vt);
            }
            tbsv.setModel(tableModel);

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbtk = new javax.swing.JComboBox();
        tk = new javax.swing.JTextField();
        jToolBar4 = new javax.swing.JToolBar();
        jButton23 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsv = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbtk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "MaSV", "TenSV", "QueQuan", "KhoaHoc", "TenLop" }));
        cbtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtkActionPerformed(evt);
            }
        });
        getContentPane().add(cbtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 177, 32));
        getContentPane().add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 220, 32));

        jToolBar4.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar4.setRollover(true);

        jButton23.setBackground(new java.awt.Color(255, 153, 204));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_25px.png"))); // NOI18N
        jButton23.setText("Tìm Kiếm");
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton23);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_account_25px.png"))); // NOI18N
        jButton4.setText("Đăng Xuất");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton4);

        getContentPane().add(jToolBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, -1, -1));

        tbsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbsv);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 920, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/tcttsv.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 610));

        jMenu1.setText("Quản Lý Sách");

        jMenuItem2.setText("QL Thể Loại");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("QL Tác Giả");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("QL Nhà XB");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("QL Sách");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý Thư Viện");

        jMenuItem6.setText("QL Ra Vào thư Viện");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("QL Phiêu Mượn Trả Sách");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem8.setText("chi Tiết Phiếu Mượn");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem10.setText("Quản Lí sách Quá Hạn Mượn");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem7.setText("Thống Kê");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setText("Tra Cứu Sinh Viên");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        String dbURL = "jdbc:sqlserver://127.0.0.1;databaseName=thuvien; user=sa;password=123";
        Connection conn;
        try {
            conn = DriverManager.getConnection(dbURL);

            Statement st = conn.createStatement();
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Mã Sinh Viên");
            tableModel.addColumn("Tên sinh Viên");
            tableModel.addColumn("DD/MM/YYY");
            tableModel.addColumn("Tên Lớp");
            tableModel.addColumn("Tên Khoa");
            tableModel.addColumn("Giới Tính");
            tableModel.addColumn("Quê Quán");
            tableModel.addColumn("Khóa Học");

            String dkien = cbtk.getSelectedItem().toString();
            String msv = tk.getText();
            String tsv = tk.getText();
            String nams = tk.getText();
            String tenl = tk.getText();
            String queq = tk.getText();
            String khoah = tk.getText();
            if (dkien.equals("Tất Cả")) {
                loadsv();

            }
            if (dkien.equals("MaSV")) {
                String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa where masv='" + msv + "' ";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("masv"));
                    vt.add(rs.getString("tensv"));
                    vt.add(rs.getString("namsinh"));
                    vt.add(rs.getString("tenlop"));
                    vt.add(rs.getString("tenkhoa"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("quequan"));
                    vt.add(rs.getString("khoahoc"));

                    //Đưa dữ liệu vào TableModel
                    tableModel.addRow(vt);
                }
                tbsv.setModel(tableModel);

            }
            if (dkien.equals("TenSV")) {
                String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa where tensv like N'" + tsv + "' ";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("masv"));
                    vt.add(rs.getString("tensv"));
                    vt.add(rs.getString("namsinh"));
                    vt.add(rs.getString("tenlop"));
                    vt.add(rs.getString("tenkhoa"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("quequan"));
                    vt.add(rs.getString("khoahoc"));

                    //Đưa dữ liệu vào TableModel
                    tableModel.addRow(vt);
                }
                tbsv.setModel(tableModel);

            }
            if (dkien.equals("NamSinh")) {
                String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa where namsinh='" + nams + "' ";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("masv"));
                    vt.add(rs.getString("tensv"));
                    vt.add(rs.getString("namsinh"));
                    vt.add(rs.getString("tenlop"));
                    vt.add(rs.getString("tenkhoa"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("quequan"));
                    vt.add(rs.getString("khoahoc"));

                    //Đưa dữ liệu vào TableModel
                    tableModel.addRow(vt);
                }
                tbsv.setModel(tableModel);

            }
            if (dkien.equals("TenLop")) {
                String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa where lop.tenlop like N'" + tenl + "' ";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("masv"));
                    vt.add(rs.getString("tensv"));
                    vt.add(rs.getString("namsinh"));
                    vt.add(rs.getString("tenlop"));
                    vt.add(rs.getString("tenkhoa"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("quequan"));
                    vt.add(rs.getString("khoahoc"));

                    //Đưa dữ liệu vào TableModel
                    tableModel.addRow(vt);
                }
                tbsv.setModel(tableModel);

            }
            if (dkien.equals("QueQuan")) {
                String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa where quequan like N'" + queq + "' ";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("masv"));
                    vt.add(rs.getString("tensv"));
                    vt.add(rs.getString("namsinh"));
                    vt.add(rs.getString("tenlop"));
                    vt.add(rs.getString("tenkhoa"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("quequan"));
                    vt.add(rs.getString("khoahoc"));

                    //Đưa dữ liệu vào TableModel
                    tableModel.addRow(vt);
                }
                tbsv.setModel(tableModel);

            }
            if (dkien.equals("KhoaHoc")) {
                String sql = "Select * from sv inner join lop on lop.malop=sv.malop inner join khoa on khoa.makhoa=lop.makhoa where khoahoc='" + khoah + "' ";
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("masv"));
                    vt.add(rs.getString("tensv"));
                    vt.add(rs.getString("namsinh"));
                    vt.add(rs.getString("tenlop"));
                    vt.add(rs.getString("tenkhoa"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("quequan"));
                    vt.add(rs.getString("khoahoc"));

                    //Đưa dữ liệu vào TableModel
                    tableModel.addRow(vt);
                }
                tbsv.setModel(tableModel);

            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TheLoaiView a = new TheLoaiView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        NhaXuatBanView a = new NhaXuatBanView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TacGiaView a = new TacGiaView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SachView a = new SachView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        TraCuuSinhVienView a = new TraCuuSinhVienView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LoginView a = new LoginView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        SachHienTaiThuVien a = new SachHienTaiThuVien();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TrangChuView a = new TrangChuView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        RaVaoView a = new RaVaoView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ChiTietPhieuMuonView a = new ChiTietPhieuMuonView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        PhieuMuonQuaHanView a = new PhieuMuonQuaHanView();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void cbtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraCuuSinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraCuuSinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraCuuSinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraCuuSinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraCuuSinhVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbtk;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTable tbsv;
    private javax.swing.JTextField tk;
    // End of variables declaration//GEN-END:variables
}
