/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import ctl.Phieumuon_ctl;
import static ctl.Phieumuon_ctl.getConnection;
import ctl.Sv_ctl;
import ctl.Sach_ctl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.phieumuon_md;
import model.sach_md;
import model.sv_md;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.*;
import com.toedter.calendar.JDateChooser;
//import com.toedter.components.JDatePanel;
//import com.toedter.components.JSpinnerButton;

public class Trangchu extends javax.swing.JFrame {

    private Phieumuon_ctl phieumuon_ctl;
    private Sach_ctl sach_ctl;
    private Sv_ctl sv_ctl;

    public Trangchu() {
        initComponents();
        phieumuon_ctl = new Phieumuon_ctl();
        sv_ctl = new Sv_ctl();
        sach_ctl = new Sach_ctl();
        addmas();
        loadphieumuon();
        Date currentDate = new Date();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        // Hiển thị ngày tháng lên JTextField
        nm.setDate(currentDate);
       nt.setDate(currentDate);
    
        nm.getDateEditor().setEnabled(false);
        nt.getDateEditor().setEnabled(false);
    }

    private void addmas() {
        try {
            List<sach_md> listkhoa = sach_ctl.addmasach();
            DefaultTableModel tb = new DefaultTableModel();
            for (sach_md a : listkhoa) {
                cbms.addItem(a.getMasach());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

//    public void tinhTongSachMuonChuaTraTheoMaSV(String maSV) {
//        DefaultTableModel tableModel = (DefaultTableModel) tbpm.getModel();
//        int tongSachMuon = 0;
//        int rowCount = tableModel.getRowCount();
//
//        for (int i = 0; i < rowCount; i++) {
//            String trangThai = tableModel.getValueAt(i, 7).toString();
//            String maSinhVien = tableModel.getValueAt(i, 1).toString();
//
//            if (trangThai.equals("Chưa Trả") && maSinhVien.equals(maSV)) {
//                tongSachMuon += Double.parseDouble(tbpm.getValueAt(i, 7).toString());
//
//            }
//
//        }
//
//    }
    private void loadphieumuon() {
        try {

            List<phieumuon_md> listlop = phieumuon_ctl.loadphieumuon();
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("Mã Phiếu Mượn");
            tb.addColumn("Mã Sinh Viên");
            tb.addColumn("Tên Sinh Viên");
            tb.addColumn("Mã Sách");
            tb.addColumn("Tên Sách");
            tb.addColumn("Ngày Mượn");
            tb.addColumn("Ngày Trả");
            tb.addColumn("Số Lượng Mượn");
            tb.addColumn("Giá Thành 1 cuốn");
            tb.addColumn("Trạng Thái");
            tb.addColumn("Ghi Chú");
            tb.addColumn("Tiền Cọc");

            for (phieumuon_md hd : listlop) {
                sv_md a = hd.getSv();
                sach_md b = hd.getSach();

                tb.addRow(new Object[]{
                    hd.getMaphieumuon(),
                    hd.getMasv(),
                    (a != null) ? a.getTensv() : "",
                    hd.getMasach(),
                    (b != null) ? b.getTensach() : "",
                    hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                    (b != null) ? b.getGiatien() : "",
                    hd.getTrangthai(), hd.getGhichu(),
                    (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                });
            }
            tbpm.setModel(tb);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        cbtk = new javax.swing.JComboBox();
        tk = new javax.swing.JTextField();
        jToolBar4 = new javax.swing.JToolBar();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mpm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        msv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbms = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        nm = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        nt = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        gc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sldm = new javax.swing.JTextField();
        cbtt = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpm = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbtk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "MaPhieuMuon", "MaSV", "MaSach", "TenSach", "TrangThai" }));
        getContentPane().add(cbtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 164, 32));
        getContentPane().add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 143, 32));

        jToolBar4.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar4.setRollover(true);

        jButton23.setBackground(new java.awt.Color(255, 153, 204));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_25px.png"))); // NOI18N
        jButton23.setText("Tìm Kiếm");
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton23);

        jButton24.setBackground(new java.awt.Color(102, 255, 51));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_25px.png"))); // NOI18N
        jButton24.setText("   Sửa   ");
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton24);

        jButton25.setBackground(new java.awt.Color(255, 51, 51));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_25px_5.png"))); // NOI18N
        jButton25.setText("   Thêm   ");
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton25);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-microsoft-excel-2019-25.png"))); // NOI18N
        jButton1.setText("Xuất Excel");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton1);

        jButton26.setBackground(new java.awt.Color(204, 255, 102));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_25px_1.png"))); // NOI18N
        jButton26.setText("    Xóa    ");
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton26);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_account_25px.png"))); // NOI18N
        jButton4.setText("Đăng Xuất");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton4);

        getContentPane().add(jToolBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 270, 460, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mã Phiếu Mượn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));
        getContentPane().add(mpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 370, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã SV");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));
        getContentPane().add(msv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 370, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã Sách");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 70, 20));

        getContentPane().add(cbms, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 370, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ngày Mượn");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        nm.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 370, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ngày Trả");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        nt.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(nt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 370, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Cọc Tiền");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 120, 40));

        tc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tc.setForeground(new java.awt.Color(255, 51, 51));
        tc.setText("jLabel11");
        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 138, -1));

        gc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcActionPerformed(evt);
            }
        });
        getContentPane().add(gc, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 332, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ghi Chú");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Trạng Thái");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Số Lượng Sách Mượn");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        sldm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldmMouseClicked(evt);
            }
        });
        sldm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sldmActionPerformed(evt);
            }
        });
        getContentPane().add(sldm, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 332, -1));

        cbtt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chưa Trả", "Đã Trả" }));
        cbtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbttActionPerformed(evt);
            }
        });
        getContentPane().add(cbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 332, -1));

        tbpm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 1430, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/phieum.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        jMenu1.setText("Quản Lí Sách");

        jMenuItem2.setText("QL Thể Loại");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("QL Tác Giả");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("QL Nhà XB");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("QL Sách");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý Thư Viện");

        jMenuItem5.setText("Quản Lí Ra Vào Thư Viện");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Quản Lí Phiếu Mượn Trả");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem6.setText("Chi Tiết Phiếu Mượn");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem10.setText("Quản Lí Sách Quá Hạn Mượn");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem9.setText("Thống Kê");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem8.setText("Tra Cứu Sinh Viên");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tacgia a = new Tacgia();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void sldmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sldmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sldmActionPerformed

    public int laysoluongsachconlai(String maSach) {
        int soLuongConLai = 0;

        try {
            Connection conn = getConnection();
            PreparedStatement stmt = conn.prepareStatement("SELECT sach.soluong - COALESCE(SUM(CASE WHEN p.trangthai = N'Chưa Trả' THEN p.soluong ELSE 0 END), 0) AS soluong_con_lai FROM sach LEFT JOIN phieumuon p ON sach.masach = p.masach WHERE sach.masach = ? GROUP BY sach.masach, sach.soluong");
            stmt.setString(1, maSach);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                soLuongConLai = rs.getInt("soluong_con_lai");
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return soLuongConLai;
    }

    public boolean kiemTraSoLuongSachMuonToiDa(String maSV) {
        boolean duocMuon = true;

        try {
            Connection conn = getConnection();
            PreparedStatement stmt = conn.prepareStatement("SELECT SUM(p.soluong) AS tong_sach FROM phieumuon p WHERE p.masv = ? AND p.trangthai like N'Chưa Trả'");
            stmt.setString(1, maSV);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                int tongSach = rs.getInt("tong_sach");

                if (tongSach >= 5) {
                    duocMuon = false;
                }
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return duocMuon;
    }

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        String mapm = mpm.getText();
        String masv = msv.getText();
        String mas = cbms.getSelectedItem().toString();

        Date ngaymuonDate = nm.getDate();

        Date ngaytraDate = nt.getDate();
        
        String sldm_text = sldm.getText();
        int sol;
        try {
            sol = Integer.parseInt(sldm_text);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng sách mượn phải là số nguyên", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String trangt = cbtt.getSelectedItem().toString();
        String ghic = gc.getText();
// Kiểm tra ngaytraDate phải lớn hơn hoặc bằng ngaymuonDate tối đa 14 ngày
        long diffInDays = (ngaytraDate.getTime() - ngaymuonDate.getTime()) / (1000 * 60 * 60 * 24);
        if (diffInDays > 14 || diffInDays < 0) {
            JOptionPane.showMessageDialog(this, "Ngày trả sách phải lớn hơn hoặc bằng ngày mượn tối đa 14 ngày", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        phieumuon_md phieumuon = new phieumuon_md(mapm, masv, mas, ngaymuonDate, ngaytraDate, sol, trangt, ghic);
        if (phieumuon_ctl.suaphieumuon(phieumuon)) {
            JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
            loadphieumuon();
             
        } else {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi sửa phiếu mượn", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        String mapm = mpm.getText();
        String masv = msv.getText();
        String mas = cbms.getSelectedItem().toString();

        Date ngaymuonDate = nm.getDate();
        Date ngaytraDate = nt.getDate();

        String sldm_text = sldm.getText();
        int sol;
        try {
            sol = Integer.parseInt(sldm_text);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng sách mượn phải là số nguyên", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String trangt = cbtt.getSelectedItem().toString();
        String ghic = gc.getText();

        int soLuongConLai = laysoluongsachconlai(mas);
// Kiểm tra ngaytraDate phải lớn hơn hoặc bằng ngaymuonDate tối đa 14 ngày
        long diffInDays = (ngaytraDate.getTime() - ngaymuonDate.getTime()) / (1000 * 60 * 60 * 24);
        if (diffInDays > 14 || diffInDays < 0) {
            JOptionPane.showMessageDialog(this, "Ngày trả sách phải lớn hơn hoặc bằng ngày mượn tối đa 14 ngày", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (soLuongConLai >= sol && kiemTraSoLuongSachMuonToiDa(masv)) {
            phieumuon_md phieumuon = new phieumuon_md(mapm, masv, mas, ngaymuonDate, ngaytraDate, sol, trangt, ghic);
            if (phieumuon_ctl.themphieumuon(phieumuon)) {
                JOptionPane.showMessageDialog(this, "Mượn Thành Công");
                loadphieumuon();
               
            } else {
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi thêm phiếu mượn", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Số lượng sách trong kho không đủ hoặc đã vượt quá số lượng sách mượn tối đa", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        String mapm = mpm.getText();
        String masv = msv.getText();
        String mas = cbms.getSelectedItem().toString();
        Date ngaym = nm.getDate();
        Date ngayt = nt.getDate();
        int sol = Integer.parseInt(sldm.getText());
        String trangt = cbtt.getSelectedItem().toString();
        String ghic = gc.getText();
        phieumuon_md hd = new phieumuon_md(mapm, masv, mas, ngaym, ngayt, sol, trangt, ghic);
        if (phieumuon_ctl.xoasphieumuon(hd)) {
            loadphieumuon();
            JOptionPane.showMessageDialog(this, "xóa dữ liệu thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Nxb a = new Nxb();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Theloai a = new Theloai();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Sach a = new Sach();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Tracuusinhvien a = new Tracuusinhvien();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void sldmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldmMouseClicked
//    

    }//GEN-LAST:event_sldmMouseClicked

    private void tbpmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpmMouseClicked
        phieumuon_ctl.click(tbpm, mpm, msv, cbms, nm, nt, sldm, cbtt, gc, tc);
    }//GEN-LAST:event_tbpmMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login1 a = new Login1();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Sachhientaithuvien a = new Sachhientaithuvien();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Ravao a = new Ravao();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Trangchu a = new Trangchu();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) tbpm.getModel();
        int columnCount = tableModel.getColumnCount();
        int rowCount = tableModel.getRowCount();

        // Tạo workbook mới
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Dữ liệu");

        // Tạo hàng tiêu đề
        Row headerRow = sheet.createRow(0);
        for (int col = 0; col < columnCount; col++) {
            String columnName = tableModel.getColumnName(col);
            Cell cell = headerRow.createCell(col);
            cell.setCellValue(columnName);
        }

        // Sao chép dữ liệu từ bảng vào workbook
        for (int row = 0; row < rowCount; row++) {
            Row dataRow = sheet.createRow(row + 1);
            for (int col = 0; col < columnCount; col++) {
                Object cellValue = tableModel.getValueAt(row, col);
                Cell cell = dataRow.createCell(col);
                if (cellValue != null) {
                    cell.setCellValue(cellValue.toString());
                }
            }
        }
        File directory = new File("FileExcelXuat");
        directory.mkdirs();
        // Lưu workbook vào tệp tin
        try (FileOutputStream fos = new FileOutputStream("FileExcelXuat/phieumuonsach.xlsx")) {
            workbook.write(fos);
            System.out.println("Xuất dữ liệu thành công!");
            JOptionPane.showMessageDialog(this, "Xuất Dữ Liệu Thành Công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        try {
            String dkien = cbtk.getSelectedItem().toString();
            String mapm = tk.getText();
            String masv = tk.getText();
            String mas = tk.getText();
            String tens = tk.getText();
            String trangt = tk.getText();

            if (dkien.equals("Tất Cả")) {
                List<phieumuon_md> listlop = phieumuon_ctl.loadphieumuon();

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Mã Phiếu Mượn");
                tb.addColumn("Mã Sinh Viên");
                tb.addColumn("Tên Sinh Viên");
                tb.addColumn("Mã Sách");
                tb.addColumn("Tên Sách");
                tb.addColumn("Ngày Mượn");
                tb.addColumn("Ngày Trả");
                tb.addColumn("Số Lượng Mượn");
                tb.addColumn("Giá Thành 1 cuốn");
                tb.addColumn("Trạng Thái");
                tb.addColumn("Ghi Chú");
                tb.addColumn("Tiền Cọc");
                for (phieumuon_md hd : listlop) {
                    sv_md a = hd.getSv();
                    sach_md b = hd.getSach();

                    tb.addRow(new Object[]{
                        hd.getMaphieumuon(),
                        hd.getMasv(),
                        (a != null) ? a.getTensv() : "",
                        hd.getMasach(),
                        (b != null) ? b.getTensach() : "",
                        hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                        (b != null) ? b.getGiatien() : "",
                        hd.getTrangthai(), hd.getGhichu(),
                        (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                    });
                }
                tbpm.setModel(tb);
            }
            if (dkien.equals("MaPhieuMuon")) {
                List<phieumuon_md> listlop = phieumuon_ctl.timkiemmaphieumuon(mapm);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Mã Phiếu Mượn");
                tb.addColumn("Mã Sinh Viên");
                tb.addColumn("Tên Sinh Viên");
                tb.addColumn("Mã Sách");
                tb.addColumn("Tên Sách");
                tb.addColumn("Ngày Mượn");
                tb.addColumn("Ngày Trả");
                tb.addColumn("Số Lượng Mượn");
                tb.addColumn("Giá Thành 1 cuốn");
                tb.addColumn("Trạng Thái");
                tb.addColumn("Ghi Chú");
                tb.addColumn("Tiền Cọc");
                for (phieumuon_md hd : listlop) {
                    sv_md a = hd.getSv();
                    sach_md b = hd.getSach();

                    tb.addRow(new Object[]{
                        hd.getMaphieumuon(),
                        hd.getMasv(),
                        (a != null) ? a.getTensv() : "",
                        hd.getMasach(),
                        (b != null) ? b.getTensach() : "",
                        hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                        (b != null) ? b.getGiatien() : "",
                        hd.getTrangthai(), hd.getGhichu(),
                        (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                    });
                }
                tbpm.setModel(tb);
            }
            if (dkien.equals("MaSach")) {
                List<phieumuon_md> listlop = phieumuon_ctl.timkiemmasach(mas);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Mã Phiếu Mượn");
                tb.addColumn("Mã Sinh Viên");
                tb.addColumn("Tên Sinh Viên");
                tb.addColumn("Mã Sách");
                tb.addColumn("Tên Sách");
                tb.addColumn("Ngày Mượn");
                tb.addColumn("Ngày Trả");
                tb.addColumn("Số Lượng Mượn");
                tb.addColumn("Giá Thành 1 cuốn");
                tb.addColumn("Trạng Thái");
                tb.addColumn("Ghi Chú");
                tb.addColumn("Tiền Cọc");
                for (phieumuon_md hd : listlop) {
                    sv_md a = hd.getSv();
                    sach_md b = hd.getSach();

                    tb.addRow(new Object[]{
                        hd.getMaphieumuon(),
                        hd.getMasv(),
                        (a != null) ? a.getTensv() : "",
                        hd.getMasach(),
                        (b != null) ? b.getTensach() : "",
                        hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                        (b != null) ? b.getGiatien() : "",
                        hd.getTrangthai(), hd.getGhichu(),
                        (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                    });
                }
                tbpm.setModel(tb);
            }
            if (dkien.equals("MaSV")) {
                List<phieumuon_md> listlop = phieumuon_ctl.timkiemmasv(masv);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Mã Phiếu Mượn");
                tb.addColumn("Mã Sinh Viên");
                tb.addColumn("Tên Sinh Viên");
                tb.addColumn("Mã Sách");
                tb.addColumn("Tên Sách");
                tb.addColumn("Ngày Mượn");
                tb.addColumn("Ngày Trả");
                tb.addColumn("Số Lượng Mượn");
                tb.addColumn("Giá Thành 1 cuốn");
                tb.addColumn("Trạng Thái");
                tb.addColumn("Ghi Chú");
                tb.addColumn("Tiền Cọc");
                for (phieumuon_md hd : listlop) {
                    sv_md a = hd.getSv();
                    sach_md b = hd.getSach();

                    tb.addRow(new Object[]{
                        hd.getMaphieumuon(),
                        hd.getMasv(),
                        (a != null) ? a.getTensv() : "",
                        hd.getMasach(),
                        (b != null) ? b.getTensach() : "",
                        hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                        (b != null) ? b.getGiatien() : "",
                        hd.getTrangthai(), hd.getGhichu(),
                        (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                    });
                }
                tbpm.setModel(tb);
            }
            if (dkien.equals("TrangThai")) {
                List<phieumuon_md> listlop = phieumuon_ctl.timkiemtrangthai(trangt);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Mã Phiếu Mượn");
                tb.addColumn("Mã Sinh Viên");
                tb.addColumn("Tên Sinh Viên");
                tb.addColumn("Mã Sách");
                tb.addColumn("Tên Sách");
                tb.addColumn("Ngày Mượn");
                tb.addColumn("Ngày Trả");
                tb.addColumn("Số Lượng Mượn");
                tb.addColumn("Giá Thành 1 cuốn");
                tb.addColumn("Trạng Thái");
                tb.addColumn("Ghi Chú");
                tb.addColumn("Tiền Cọc");
                for (phieumuon_md hd : listlop) {
                    sv_md a = hd.getSv();
                    sach_md b = hd.getSach();

                    tb.addRow(new Object[]{
                        hd.getMaphieumuon(),
                        hd.getMasv(),
                        (a != null) ? a.getTensv() : "",
                        hd.getMasach(),
                        (b != null) ? b.getTensach() : "",
                        hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                        (b != null) ? b.getGiatien() : "",
                        hd.getTrangthai(), hd.getGhichu(),
                        (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                    });
                }
                tbpm.setModel(tb);
            }
            if (dkien.equals("TenSach")) {
                List<phieumuon_md> listlop = phieumuon_ctl.timkiemtensach(tens);

                DefaultTableModel tb = new DefaultTableModel();
                tb.addColumn("Mã Phiếu Mượn");
                tb.addColumn("Mã Sinh Viên");
                tb.addColumn("Tên Sinh Viên");
                tb.addColumn("Mã Sách");
                tb.addColumn("Tên Sách");
                tb.addColumn("Ngày Mượn");
                tb.addColumn("Ngày Trả");
                tb.addColumn("Số Lượng Mượn");
                tb.addColumn("Giá Thành 1 cuốn");
                tb.addColumn("Trạng Thái");
                tb.addColumn("Ghi Chú");
                tb.addColumn("Tiền Cọc");
                for (phieumuon_md hd : listlop) {
                    sv_md a = hd.getSv();
                    sach_md b = hd.getSach();

                    tb.addRow(new Object[]{
                        hd.getMaphieumuon(),
                        hd.getMasv(),
                        (a != null) ? a.getTensv() : "",
                        hd.getMasach(),
                        (b != null) ? b.getTensach() : "",
                        hd.getNgaymuon(), hd.getNgaytra(), hd.getSoluong(),
                        (b != null) ? b.getGiatien() : "",
                        hd.getTrangthai(), hd.getGhichu(),
                        (b != null) ? hd.getSoluong() * b.getGiatien() * 1.5 : 0.0

                    });
                }
                tbpm.setModel(tb);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Chitietphieumuon a = new Chitietphieumuon();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void cbttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbttActionPerformed

    private void gcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gcActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Phieumuonquahan a = new Phieumuonquahan();
        a.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trangchu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbms;
    private javax.swing.JComboBox cbtk;
    private javax.swing.JComboBox cbtt;
    private javax.swing.JTextField gc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTextField mpm;
    private javax.swing.JTextField msv;
    private com.toedter.calendar.JDateChooser nm;
    private com.toedter.calendar.JDateChooser nt;
    private javax.swing.JTextField sldm;
    private javax.swing.JTable tbpm;
    private javax.swing.JLabel tc;
    private javax.swing.JTextField tk;
    // End of variables declaration//GEN-END:variables
}
