/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.khoa_md;
import model.lop_md;
import ctl.Lop_ctl;
import ctl.Khoa_ctl;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileOutputStream;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
public class Lop extends javax.swing.JFrame {
private Khoa_ctl khoa_ctl;
    private Lop_ctl lop_ctl;
    public Lop() {
        initComponents();
        lop_ctl=new Lop_ctl(); 
        khoa_ctl=new Khoa_ctl();
        loadlop();
      
        addmk();
    }
     private void addmk(){
 try{
            List<khoa_md> listkhoa = khoa_ctl.addmakhoa();
             DefaultTableModel tb = new DefaultTableModel();
            for(khoa_md a : listkhoa){
                cbmk.addItem(a.getMakhoa());
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
private void loadlop(){
        try{ 
            lop_ctl = new Lop_ctl();
            List<lop_md> listlop = lop_ctl.loadlop();
             DefaultTableModel tb = new DefaultTableModel();
           
            tb.addColumn("Mã Lớp");
            tb.addColumn("tên Lớp");
            tb.addColumn("Tên khoa");
            tb.addColumn("Ghi Chú");
            for(lop_md hd : listlop){
                khoa_md a = hd.getKhoa();
                tb.addRow(new Object[]{
                
                    hd.getMalop(),hd.getTenlop(), 
                    (a !=null) ? a.getTenkhoa() : "",
                    hd.getGhichu()
                
                   
                });
            }
            tbl.setModel(tb);
        }catch(Exception ex){
            ex.printStackTrace();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbtk = new javax.swing.JComboBox();
        tk = new javax.swing.JTextField();
        jToolBar4 = new javax.swing.JToolBar();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ml = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbmk = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbtk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "MaLop", "TenLop", "TenKhoa" }));
        getContentPane().add(cbtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 130, 32));
        getContentPane().add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 170, 32));

        jToolBar4.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar4.setRollover(true);

        jButton23.setBackground(new java.awt.Color(255, 153, 204));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_25px.png"))); // NOI18N
        jButton23.setText("Tìm Kiếm");
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton23);

        jButton24.setBackground(new java.awt.Color(102, 255, 51));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_25px.png"))); // NOI18N
        jButton24.setText("   Sửa   ");
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton24);

        jButton25.setBackground(new java.awt.Color(255, 51, 51));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_25px_5.png"))); // NOI18N
        jButton25.setText("   Thêm   ");
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton25);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-microsoft-excel-2019-25.png"))); // NOI18N
        jButton1.setText("Xuất Excel");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton1);

        jButton26.setBackground(new java.awt.Color(204, 255, 102));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_25px_1.png"))); // NOI18N
        jButton26.setText("    Xóa    ");
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton26);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_account_25px.png"))); // NOI18N
        jButton4.setText("Đăng Xuất");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton4);

        getContentPane().add(jToolBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 180, 460, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã Lớp");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));
        getContentPane().add(ml, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên Lớp");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));
        getContentPane().add(tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 400, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ghi Chú");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));
        getContentPane().add(gc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 400, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mã Khoa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        getContentPane().add(cbmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 400, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 840, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/lh.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 670));

        jMenu2.setText("Quản Lý Chung");

        jMenuItem5.setText("Quản Lí Thông Tin Sinh Viên");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Quản Lí Khoa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem6.setText("Quản Lí Lớp");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         Lop a=new Lop();
      a.show();
      this.hide();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         Admin a=new Admin();
      a.show();
      this.hide();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         Khoa a=new Khoa();
      a.show();
      this.hide();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
     String malop = ml.getText().trim();
        String tenlp = tl.getText().trim();
      
        String makhoa = cbmk.getSelectedItem().toString();
        String ghichu = gc.getText().toString();
            if (malop.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã lớp", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (tenlp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên lớp", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

      lop_md hd = new lop_md(malop,tenlp,ghichu,makhoa);
        if(lop_ctl.sualop(hd)){
            loadlop();
              JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
        }else{
            JOptionPane.showMessageDialog(this,"Lỗi khi sửa dữ liệu","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
          String malop = ml.getText().trim();
        String tenlp = tl.getText().trim();
      
        String makhoa = cbmk.getSelectedItem().toString();
        String ghichu = gc.getText().toString();
            if (malop.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã lớp", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (tenlp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên lớp", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        lop_md hd = new lop_md(malop,tenlp,ghichu,makhoa);
        if(lop_ctl.themlop(hd)){
            loadlop();
             JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công");
        }else{
            JOptionPane.showMessageDialog(this,"Lỗi khi thêm dữ liệu","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        String malop = ml.getText();
        String tenlp = tl.getText();
        String ghichu = gc.getText();
        String makhoa = cbmk.getSelectedItem().toString();
        lop_md hd = new lop_md(malop,tenlp,ghichu,makhoa);
        if(lop_ctl.xoalop(hd)){
            loadlop();
            JOptionPane.showMessageDialog(this, "xóa dữ liệu thành công");
        }else{
            JOptionPane.showMessageDialog(this,"Lỗi khi xóa dữ liệu ","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
  
       try{
            String dkien=cbtk.getSelectedItem().toString();
            String malop = tk.getText();
              String tenlop = tk.getText();
                String tenkhoa = tk.getText();
                 String makhoa = tk.getText();
               if(dkien.equals("Tất Cả")){
            List<lop_md> listhd = lop_ctl.loadlop();
             DefaultTableModel tb = new DefaultTableModel();
           
            tb.addColumn("Mã Lớp");
            tb.addColumn("tên Lớp");
            tb.addColumn("Tên khoa");
            tb.addColumn("Ghi Chú");
            for(lop_md hd : listhd){
                khoa_md a = hd.getKhoa();
                tb.addRow(new Object[]{
                
                    hd.getMalop(),hd.getTenlop(), 
                    (a !=null) ? a.getTenkhoa() : "",
                    hd.getGhichu()
                
                   
                });
            }
            tbl.setModel(tb);
            }   
            if(dkien.equals("MaLop")){
            List<lop_md> listhd = lop_ctl.timkiemmalop(malop);
             DefaultTableModel tb = new DefaultTableModel();
           
            tb.addColumn("Mã Lớp");
            tb.addColumn("tên Lớp");
            tb.addColumn("Tên khoa");
            tb.addColumn("Ghi Chú");
            for(lop_md hd : listhd){
                khoa_md a = hd.getKhoa();
                tb.addRow(new Object[]{
                
                    hd.getMalop(),hd.getTenlop(), 
                    (a !=null) ? a.getTenkhoa() : "",
                    hd.getGhichu()
                
                   
                });
            }
            tbl.setModel(tb);
            }
                    if(dkien.equals("TenLop")){
            List<lop_md> listhd = lop_ctl.timkiemtenlop(tenlop);
              DefaultTableModel tb = new DefaultTableModel();
           
            tb.addColumn("Mã Lớp");
            tb.addColumn("tên Lớp");
            tb.addColumn("Tên khoa");
            tb.addColumn("Ghi Chú");
            for(lop_md hd : listhd){
                khoa_md a = hd.getKhoa();
                tb.addRow(new Object[]{
                
                    hd.getMalop(),hd.getTenlop(), 
                    (a !=null) ? a.getTenkhoa() : "",
                    hd.getGhichu()
                
                   
                });
            }
            tbl.setModel(tb);
            }
               
            if(dkien.equals("TenKhoa")){
                 
            List<lop_md> listhd = lop_ctl.timkiemtenkhoa(tenkhoa);
             DefaultTableModel tb = new DefaultTableModel();
           
            tb.addColumn("Mã Lớp");
            tb.addColumn("tên Lớp");
            tb.addColumn("Tên khoa");
            tb.addColumn("Ghi Chú");
            for(lop_md hd : listhd){
                khoa_md a = hd.getKhoa();
                tb.addRow(new Object[]{
                
                    hd.getMalop(),hd.getTenlop(), 
                    (a !=null) ? a.getTenkhoa() : "",
                    hd.getGhichu()
                
                   
                });
            }
            tbl.setModel(tb);
            }
                    if(dkien.equals("MaKhoa")){
                 
            List<lop_md> listhd = lop_ctl.timkiemmakhoa(makhoa);
             DefaultTableModel tb = new DefaultTableModel();
           
            tb.addColumn("Mã Lớp");
            tb.addColumn("tên Lớp");
            tb.addColumn("Tên khoa");
            tb.addColumn("Ghi Chú");
            for(lop_md hd : listhd){
                khoa_md a = hd.getKhoa();
                tb.addRow(new Object[]{
                
                    hd.getMalop(),hd.getTenlop(), 
                    (a !=null) ? a.getTenkhoa() : "",
                    hd.getGhichu()
                
                   
                });
            }
            tbl.setModel(tb);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
       lop_ctl.click(tbl,cbmk,ml,tl,gc);
    }//GEN-LAST:event_tblMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Login1 a=new Login1();
       a.show();
       this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) tbl.getModel();
        int columnCount = tableModel.getColumnCount();
        int rowCount = tableModel.getRowCount();

        // Tạo workbook mới
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Dữ liệu");

        // Tạo hàng tiêu đề
        Row headerRow = sheet.createRow(0);
        for (int col = 0; col < columnCount; col++) {
            String columnName = tableModel.getColumnName(col);
            Cell cell = headerRow.createCell(col);
            cell.setCellValue(columnName);
        }

        // Sao chép dữ liệu từ bảng vào workbook
        for (int row = 0; row < rowCount; row++) {
            Row dataRow = sheet.createRow(row + 1);
            for (int col = 0; col < columnCount; col++) {
                Object cellValue = tableModel.getValueAt(row, col);
                Cell cell = dataRow.createCell(col);
                if (cellValue != null) {
                    cell.setCellValue(cellValue.toString());
                }
            }
        }
        File directory = new File("FileExcelXuat");
        directory.mkdirs();
        // Lưu workbook vào tệp tin
        try (FileOutputStream fos = new FileOutputStream("FileExcelXuat/lop.xlsx")) {
            workbook.write(fos);
            System.out.println("Xuất dữ liệu thành công!");
            JOptionPane.showMessageDialog(this, "Xuất Dữ Liệu Thành Công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbmk;
    private javax.swing.JComboBox cbtk;
    private javax.swing.JTextField gc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTextField ml;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tk;
    private javax.swing.JTextField tl;
    // End of variables declaration//GEN-END:variables
}
